import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/app/Context/UserContext";
import { ThemeProvider } from "@/app/Context/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <ThemeProvider>
          <body className={inter.className}>{children}</body>
        </ThemeProvider>
      </UserProvider>
    </html>
  );
}
